### PR TITLE
Fix and localisation update 

### PR DESCRIPTION
**Pull request by Rekandy**
Correction of translation errors and translation of new text. There was also a little work done to change the style of the text

### CODE REVIEW

**Comment by chr233** [comment]
thanks a lot

**Comment by Rekandy** [comment]
I also updated incorrect commands and errors in the names of parameters, but something went wrong and in the end I broke it, now I will know that making backups is the most important thing in writing code😁, so I’ll come back after collage and try to check and fix everything

**Comment by Rekandy** [comment]
If nothing works out, I’ll do it all over again in 1-2 days

**Comment by Rekandy** [comment]
What has been fixed:
1. fixed ASFTradeExtension command
2. fixed SengTradeSuccess to SendTradeSuccess
3. changed incorrect translation of avilable to available 
chrome_YbK0K5hHDe
4. Added English translation
5. Complete translation of Chinese text in Russian localisation

P.S. I recommend checking first before adding to the main repository for bugs, as I may have missed something

**Comment by chr233** [comment]
为什么无法合并呢

**Comment by Rekandy** [comment]
由于纠正了错误的 "数据名称"，如 "SengTradeSuccess"、"SendTradeFailedNoItemAvilable"、"NoAvilableItemToShow"，因此出现了文件冲突"。

**Comment by chr233** [comment]
just commit Langs.ru-RU.resx only

**Pull request merged**
